# config.properties
db.url=
db.user=
db.pass=
DEV_ALLOW_NO_LICENSE =
trx.prefix=
trx.number_length=
company.name=
company.address=
company.city=
fee.payment.online.postpaid=2500
fee.payment.online.prepaid=2500
fee.payment.online.prepaid.non.nominal=1000
profile=dev
token.prod=
token.dev=
username=085647642539
url.prepaid.prod=
url.prepaid.dev=
url.postpaid.prod=
url.postpaid.dev=


