# config.properties
db.url=jdbc:mariadb://127.0.0.1:3306/babsnet
db.user=root
db.pass=12345678
DEV_ALLOW_NO_LICENSE =false
trx.prefix=KIA
trx.number_length=5
company.name=CV. BABSNET
company.address=JL. YOUR ADDRESS NO. 123
company.city=Bumiayu
fee.payment.online.postpaid=2500
fee.payment.online.prepaid=2500
fee.payment.online.prepaid.non.nominal=1000
profile=dev
token.prod=99468ebd37b821f9Mpud
token.dev=67061455deb25a0a
username=085647642539
url.prepaid.prod=https://prepaid.iak.id
url.prepaid.dev=https://prepaid.iak.dev
url.postpaid.prod=https://mobilepulsa.net
url.postpaid.dev=https://testpostpaid.mobilepulsa.net


